### ISSUE TITLE
Allow downloadable HTML export of DB

### ISSUE THREAD

**Issue by tigerhawkvok** [SSARHERPS/SSAR-species-database#40]

**Comment by tigerhawkvok** [comment]
Do we want this an an option? Or is the CSV good enough?

**Comment by mkoo** [comment]
CSV is a good option, download is fast; however, downloadable fields should omit "Taxon Author" which has last edited by name.

A few authorities broke upon csv output:
Ambystoma mavortium mavortium Baird 1850 '1849' --> baird 
Plestiodon egregius Baird 1949 "1848" --> Baird 1959 '1858""

Also, all diacritics came out non-UTF-8; any way to force UTF8?

**Comment by mkoo** [comment]
forgot to answer your question: yes, keep this option (also great way to check data!)

**Comment by tigerhawkvok** [comment]
>Also, all diacritics came out non-UTF-8; any way to force UTF8?

It's a basic problem in Excel -- it assumes ANSI for all CSV. However, there is a linkout to instructions:

https://github.com/SSARHERPS/SSAR-species-database/blob/master/meta/excel_unicode_readme.md

(with screenshots!)

**Comment by mkoo** [comment]
great ReadMe!
