### ISSUE TITLE
Add flag for Alien species?

### ISSUE THREAD

**Issue by mkoo** [SSARHERPS/SSAR-species-database#51]
We have about 8 pages of alien species to add as they are established species in N.A.  
Should we allow searches to include/exclude alien species? Or not worry about it and just add them to the CNDB? If we do want this feature, would be easier to implement on creating these records than afterward.  
I'll ask committee too.

**Comment by tigerhawkvok** [comment]
I think **definitely** a database flag, and I'll try to get that on the admin side quickly.

I'm undecided on how to do it on the search, but exposing data that are there can happen at any point, the important point is the structured data itself.
