### ISSUE TITLE
Alien species in UI

### ISSUE THREAD

**Issue by tigerhawkvok** [SSARHERPS/SSAR-species-database#52]
How should alien species be displayed? See #51 .

1. ~~Should the search be different?~~
  1. ~~If so, what default?~~
2. Should this be flagged in the general result list?
3. ~~How should the UI expose this in the overlay dialog?~~ Tentative implementation as of 14866b5109770abd766fd79b830d75deb5833c09

**Comment by tigerhawkvok** [comment]
Removing block with closure of #51 . Tentative user-facing label ( see http://ssarherps.org/cndb/#dXRhaHJhcHRvciZsb29zZT10cnVl ), still undecided on points 1 and 2 here.

**Comment by tigerhawkvok** [comment]
As of acaf14a317d38c0fbb4ba3190b36ac13d7f443b4 , showing alien species under "Advanced" as a set of three radio choices:

![image](https://cloud.githubusercontent.com/assets/165937/8145936/6b566c98-11d2-11e5-9a89-190702a8d37d.png)

**Comment by tigerhawkvok** [comment]
For the alien icon, I'm currently using a plane -- the other icons I was working from are

- [polymer core set](http://ssarherps.org/cndb/bower_components/core-icons/demo.html) (free)
- [Glyphicons](http://glyphicons.com/) (purchased by me)

Though I'm open to other suggestions. Possibly [the alien emoji &#128125;](http://unicode-table.com/en/1F47D/) ?

**Comment by mkoo** [comment]
Looking good!
I played around with Dendrobates auratus, and like the public interface with the plane icon. Clever! I was thinking of a luggage icon (glyphicons has one I think in the free set), but I like the plane better. Tool tips help a lot too.

Advanced help options--> can remove the first two words "Alien Species" as it doesnt add anything; Radio button options are sufficient.

**Comment by tigerhawkvok** [comment]
FWIW I already have a purchased Glyphicons ;-)

**Comment by tigerhawkvok** [comment]
I'll mark it as `sr-only` for accessibility reasons

**Comment by tigerhawkvok** [comment]
Closing for now, I'll re-open if there are any issues
