### ISSUE TITLE
bulkload taxon credit and date for salamanders

### ISSUE THREAD

**Issue by atrox10** [SSARHERPS/SSAR-species-database#62]
can michelle or philip do this? all salamanders need this taxon credit and date:

Stephen G. Tilley (Chair), Richard Highton, David B. Wake
2014-07-10

**Comment by mkoo** [comment]
I see that we posted this previously: 
  
    UPDATE `north_american_species` SET `taxon_credit_date`="2014-07-10" WHERE (`taxon_credit_date`="" AND `taxon_credit`="Stephen G. Tilley (Chair), Richard Highton, David B. Wake" AND `linnean_order`="caudata" );

So need to adjust:
  
    UPDATE `north_american_species` SET `taxon_credit_date`="2014-07-10" AND `taxon_credit`="Stephen G. Tilley (Chair), Richard Highton, David B. Wake"  WHERE (`taxon_credit_date`="" AND `linnean_order`="caudata" );

**Comment by tigerhawkvok** [comment]
Ran

```sql
UPDATE  `north_american_species` SET  `taxon_credit_date` =  "2014-07-10", `taxon_credit` =  "Stephen G. Tilley (Chair), Richard Highton, David B. Wake" WHERE (`taxon_credit_date` =  "" AND  `linnean_order` =  "caudata")
```

Updating 198 records
