### ISSUE TITLE
issue with subclade names not being capitalized and showing up in not obvious spot

### ISSUE THREAD

**Issue by atrox10** [SSARHERPS/SSAR-species-database#71]
Hey All

So I added all the subgenus names for Anolis and Phrynosoma. These are basically subclades for these taxa.

They are showing up when you click on the species, but the name is not capitalized (see Phrynosoma blainvillii). It says (anota)/phrynosomatidae

for subclade/family.

First these need to be capitalized.

And second for these taxa (Anolis and Phrynosoma) do we want them to show up like they did in the original document, which is like this

Phrynsoma (Anota) blainvillii
?

And these don't show up at all when printing out the html. That would be useful to include somehow.
Thanks
Carol

**Comment by tigerhawkvok** [comment]
What are the generalized rules for subgenera / subclades?

The best I could find was [Phylocode Article 10](https://www.ohio.edu/phylocode/art10.html), which says subclades should be denoted as, eg, *Phyrnosoma-Anota* (which would make me change parsing to allow a dash in genus):

As per 10F:

>Example 2. If one were selecting a name for the animal clade corresponding in composition to the subgenus *Crotaphytus* of the genus *Crotaphytus* Holbrook, and if the name *Crotaphytus* could not be converted for that clade because that name had already been established under this code for a clade corresponding in composition with the genus, the name that should be selected is *Crotaphytus-Crotaphytus* (provided that there is no other preexisting name that has been widely and recently applied to this clade)

I could find no other canonical reference / example in Phylocode, and none at all in the ICZN with [article 44](http://www.nhm.ac.uk/hosted-sites/iczn/code/index.jsp?nfv=true&article=44#1) and [article 67](http://www.nhm.ac.uk/hosted-sites/iczn/code/index.jsp?nfv=true&article=67), which at best suggests mentioning the other genus inline:

> **Example.** *Astacus marinus* Fabricius, 1775, one of the nominal species originally included in the decapod crustacean genus *Homarus* Weber, 1795, was subsequently designated by Fowler (1912) as the type species of *Homarus*. The type species is, and should be cited as, *Astacus marinus* Fabricius, 1775. *Astacus marinus* Fabricius is currently synonymized with *Cancer gammarus* Linnaeus, 1758, but the latter is not the type species of *Homarus* and should not be cited as such. If mention of the type species is required it should be made in some such manner as "Type species *Astacus marinus* Fabricius, 1775, a junior synonym of *Cancer gammarus* Linnaeus, 1758"; or "Type species *Astacus marinus* Fabricius, 1775, now regarded as a synonym of *Homarus gammarus* (Linnaeus, 1758)".

Which makes it unclear how to proceed.

Even if it's always parenthetical, we should come up with a standardized formatting so it can be intelligently parsed / displayed.

**Comment by atrox10** [comment]
So for our purposes, I think the only subclades we have are for Anolis and
Phrynsoma.
On the original entries from Brian Crother, they had them like this
Phrynosoma (Anota) blainvillii

etc.

So between Genus and species, in parentheses and capitalized. I am not sure
if we had any listed for frogs or salamanders.

If it's only for those two Genera, maybe we can do something specific for
them?


On Mon, Jul 20, 2015 at 2:10 PM, Philip Kahn <notifications@github.com>
wrote:

> What are the generalized rules for subgenera / subclades?
>
> The best I could find was Phylocode Article 10
> <https://www.ohio.edu/phylocode/art10.html>, which says subclades should
> be denoted as, eg, *Phyrnosoma-Anota* (which would make me change parsing
> to allow a dash in genus):
>
> As per 10F:
>
> Example 2. If one were selecting a name for the animal clade corresponding
> in composition to the subgenus *Crotaphytus* of the genus *Crotaphytus*
> Holbrook, and if the name *Crotaphytus* could not be converted for that
> clade because that name had already been established under this code for a
> clade corresponding in composition with the genus, the name that should be
> selected is *Crotaphytus-Crotaphytus* (provided that there is no other
> preexisting name that has been widely and recently applied to this clade)
>
> I could find no other canonical reference / example in Phylocode, and none
> at all in the ICZN with article 44
> <http://www.nhm.ac.uk/hosted-sites/iczn/code/index.jsp?nfv=true&article=44#1>
> and article 67
> <http://www.nhm.ac.uk/hosted-sites/iczn/code/index.jsp?nfv=true&article=67>,
> which at best suggests mentioning the other genus inline:
>
> *Example.* *Astacus marinus* Fabricius, 1775, one of the nominal species
> originally included in the decapod crustacean genus *Homarus* Weber,
> 1795, was subsequently designated by Fowler (1912) as the type species of
> *Homarus*. The type species is, and should be cited as, *Astacus marinus*
> Fabricius, 1775. *Astacus marinus* Fabricius is currently synonymized
> with *Cancer gammarus* Linnaeus, 1758, but the latter is not the type
> species of *Homarus* and should not be cited as such. If mention of the
> type species is required it should be made in some such manner as "Type
> species *Astacus marinus* Fabricius, 1775, a junior synonym of *Cancer
> gammarus* Linnaeus, 1758"; or "Type species *Astacus marinus* Fabricius,
> 1775, now regarded as a synonym of *Homarus gammarus* (Linnaeus, 1758)".
>
> Which makes it unclear how to proceed.
>
> Even if it's always parenthetical, we should come up with a standardized
> formatting so it can be intelligently parsed / displayed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SSARHERPS/SSAR-species-database/issues/71#issuecomment-123040580>
> .
>



-- 
Carol L. Spencer, Ph.D.
Staff Curator of Herpetology & Researcher
Museum of Vertebrate Zoology
3101 Valley Life Sciences Building
University of California, Berkeley, CA, USA 94720-3160
atrox10@gmail.com  and  atrox@berkeley.edu
510-643-5778 /FAX: 510-643-8238

http://www.herpnet.org
http://mvz.berkeley.edu/
http://www.vertnet.org

**Comment by tigerhawkvok** [comment]
It won't be too different a scope change between a generalized and specific solution, so we might as well do it right!

**Comment by tigerhawkvok** [comment]
Closing, moving re-scoped issue to #74
