### ISSUE TITLE
Thumbnails in popups interfere with species name

### ISSUE THREAD

**Issue by mkoo** [SSARHERPS/SSAR-species-database#72]
Species name should be top of popup, free of image obstruction!

**Comment by mkoo** [comment]
mostly a problem when no taxon notes to stretch out the box but need a universal solution. 
Eg of popup: (Maybe add wider margin around thumbnail)
![screen shot 2015-07-21 at 11 35 13 am](https://cloud.githubusercontent.com/assets/2523089/8809318/ca39206a-2f9c-11e5-81c2-e0d72cc4066e.png)

**Comment by tigerhawkvok** [comment]
I'll just push it down a touch.

At the EBV today but my goal is to leave early, and I'll take care of this no later than then.

**Comment by tigerhawkvok** [comment]
Note to self: add margin to top of image, and on media query larger than 767px enforce a minimum width in em

**Comment by tigerhawkvok** [comment]
Fixed on polymer1.0 branch and master

![screenshot 2015-07-21 18 24 19](https://cloud.githubusercontent.com/assets/165937/8815991/be0e9b2e-2fd5-11e5-9819-7969908cfb51.png)
