### ISSUE TITLE
change all lizards to lizard

### ISSUE THREAD

**Issue by atrox10** [SSARHERPS/SSAR-species-database#73]
Hi all
I emailed you but I am at work now so figured I would add it to the list. Can you change all the "lizards" to "lizard" in Major Common Type? for non-snake lizards

Thanks!
carol

**Comment by tigerhawkvok** [comment]
Ran 

```sql
UPDATE `north_american_species` SET `major_common_type`="lizard" WHERE `major_common_type`="lizards"
```

Updating 74 records.
