### ISSUE TITLE
Differing taxonomy in external sites (eg. Reptile-database, CalPhotos, AW) lead... no where?

### ISSUE THREAD

**Issue by mkoo** [SSARHERPS/SSAR-species-database#77]
Likely have to have different solutions for each to include synonymies in search term. Meanwhile, an equivalent 404 response for user feedback when such a search is not working?

Eg. Lampropeltis multifasciatus in CNDB --> no results
Search manually on Reptile-database returns its synonymy L.zonata multifasciatus
(http://reptile-database.reptarium.cz/species?genus=Lampropeltis&species=zonata&search_param=%28%28search%3D%27Lampropeltis+multifasciata%27%29%29)

**Comment by tigerhawkvok** [comment]
I'll shoot them an email and see if I can get an API endpoint.

If they have it, I can hit it for results, then then remove the button if the target doesn't exist.

Another option may be to after pinging the remote, if there are no results, pinging the remote on the "deprecated scientific" names, and linking "for real" when results are found (though this specific example seems that the deprecateds were never filled out).

**Comment by tigerhawkvok** [comment]
They're on the ball, those guys:

> Hi Philip,
> 
> you can try our service http://reptile-database.reptarium.cz/interfaces/services/check-taxon with parameter "taxon"
> 
> eg:
> http://reptile-database.reptarium.cz/interfaces/services/check-taxon?taxon=Lampropeltis+zonata
> http://reptile-database.reptarium.cz/interfaces/services/check-taxon?taxon=Lampropeltis+multifasciata
> http://reptile-database.reptarium.cz/interfaces/services/check-taxon?taxon=Lampropeltis+multifasciatus
> 
> Respons is in JSON format with clear syntax.
> 
> Is it useful for you?
> 
> Best regards, Jiri

So, pinging our sample, we'd get

```json
{
  "VALID": [
    "Lampropeltis zonata"
  ],
  "description": "Specified taxon has been found as synonym for: Lampropeltis zonata.",
  "response": "SYNONYM"
}
```

So if the `response` is `SYNONYM`, I can have it re-link to the `result.VALID[0]`

**Comment by tigerhawkvok** [comment]
Looks like we're blocked on CORS again -- just emailed them about it.

**Comment by tigerhawkvok** [comment]
They're very on the ball.

>Done, CORS is enabled for this service
>
>Jiri

**Comment by tigerhawkvok** [comment]
Also used the Reptile Database lookup to see if CalPhotos recognizes their alternate taxon, with the SSAR species as the subspecies -- and if it does, using that as the link and image source.

See http://ssarherps.org/cndb/polymer1beta/#bGFtcHJvcGVsdGlzK211bHRpZmFzY2lhdGEmbG9vc2U9dHJ1ZQ as an example.
