### ISSUE TITLE
mystery search results

### ISSUE THREAD

**Issue by mkoo** [SSARHERPS/SSAR-species-database#81]
Not sure what is going on but some searches result in species that do not seem to have anything to do with the search term.

Ex. Search on 'avivoca'
Returns, the appropriate hyla avivoca and subspecies AND Crotalus?

![screenshot-ssarherps org 2015-09-03 11-46-11](https://cloud.githubusercontent.com/assets/2523089/9667618/a8690fa6-5231-11e5-937f-5644c066caa9.png)

**Comment by tigerhawkvok** [comment]
It's the "fuzzy" flag -- it's looking for misspellings of "avivoca", which is including "abyssus" here as "closesish".
