### ISSUE TITLE
Eurycea longicauda longicauda Common Name Error

### ISSUE THREAD

**Issue by j2ma** [SSARHERPS/SSAR-species-database#86]
The common name for Eurycea l. longicauda is 'Eztern' as listed, but is most likely a misspelling of 'Eastern'.

![capture](https://cloud.githubusercontent.com/assets/14501694/9984156/cbee21e8-5fe0-11e5-9eb9-5ff4dee69f69.JPG)

**Comment by mkoo** [comment]
Typo fixed.
