### ISSUE TITLE
Common name fields need to remove title case formatting

### ISSUE THREAD

**Issue by gordonhlau** [SSARHERPS/SSAR-species-database#87]
E.g. Plethodon hubrichti, Peaks Of Otter Salamander (need to remove capitalization in "Of")

**Comment by mkoo** [comment]
Reopening since the preposition 'Of' is not cooperating.
See Plethodon hubrichti's common name:
Peaks Of Otter Salamander

**Comment by mkoo** [comment]
Also, another rule: lower case when following a hyphen.
EG. Yellow-bellied, Narrow-mouthed, etc

**Comment by tigerhawkvok** [comment]
@mkoo "of" looks like it's already fixed --

![image](https://cloud.githubusercontent.com/assets/165937/19457133/bc141916-9479-11e6-984c-f079b0fd303f.png)

The file:

[ssar-common-names-2016-10-17.zip](https://github.com/SSARHERPS/SSAR-species-database/files/534778/ssar-common-names-2016-10-17.zip)

**Comment by tigerhawkvok** [comment]
Fixed dashes

![image](https://cloud.githubusercontent.com/assets/165937/19458273/eb4b9b4a-947f-11e6-8dd7-99f2d94e6a13.png)

![image](https://cloud.githubusercontent.com/assets/165937/19458274/f06750d8-947f-11e6-9153-44598c9f454a.png)
