### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by spinifer** [SSARHERPS/SSAR-species-database#91]
1. English name for Coal Skink is spelled "sink" in all species and subspecies
2. Mountain Skink and Mole Skink...same as above
3. English name for Barking Treefrog is pluralized

**Comment by bruhe** [comment]
Hey SSAR, get on Spinifer's comments! 

English name for Coal Skink is spelled "sink" in all species and subspecies
Mountain Skink and Mole Skink...same as above
English name for Barking Treefrog is pluralized

**Comment by bruhe** [comment]
Thank you mkoo and keep up the great work.
